encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.entry_page, name="entryPage"),
    path("wiki/<str:title>/edit", views.edit_existing_page, name="editPage"),
    path("new_page/", views.create_new_page, name="createNewPage"),
    path("random_page", views.select_random_page, name="randomPage"),
    path("search/<str:searchTerm>", views.search_results, name="searchResults")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/forms.py
from django import forms
from . import util

class CreatePageForm(forms.Form):
   title = forms.CharField(label='Title')
   content = forms.CharField(label='', widget=forms.Textarea())

class EditPageForm(forms.Form):
   content = forms.CharField(label='', widget=forms.Textarea)

encyclopedia/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpRequest

from random import randint
from . import util
from .forms import CreatePageForm, EditPageForm # dont understand why


def index(request):
    getParameter = request.GET # retrieves the GET parameter.

    if util.listen_for_search(getParameter): # listens for user searching for a page.
        return util.search_for_page(getParameter)
    else:
        return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def entry_page(request, title):
    getParameter = request.GET

    if util.listen_for_search(getParameter): # listens for user searching for a page.
        return util.search_for_page(getParameter)

    if title in util.list_entries():    
        templateBodyContent = util.markdown_to_html_coverter(title)
        context = { 'title': title,
                    'bodyContent': templateBodyContent}
        return render(request, "encyclopedia/page.html", context)
    else:
        return HttpResponse('<h1>404. Page not found.<h1>')
    

def create_new_page(request):
    if request.method == 'POST':
        form = CreatePageForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            markdownPage = util.save_entry(title, content)
            htmlPage = util.markdown_to_html_coverter(title)
            return redirect('encyclopedia:entryPage', title)
    else:
        form = CreatePageForm()
    return render(request, "encyclopedia/createpage.html", {"form": form})


def edit_existing_page(request, title):
    content = util.get_entry(title)
    data = {"content": content}
    form = EditPageForm(initial=data)
    if request.method == 'GET':
        return render(request, "encyclopedia/editpage.html", {"form": form, "title": title})
    else:
        content = request.POST['content']
        with open(f"./entries/{title}.md", "w") as f:
            f.write(content)
        html = util.markdown_to_html_coverter(title)
        return redirect('encyclopedia:entryPage', title)


def select_random_page(request):
    pageTitleList = util.list_entries()
    randomIndex = randint(0, len(pageTitleList) - 1)
    randomPageTitle = pageTitleList[randomIndex]
    return redirect('wiki/' + randomPageTitle)


def search_results(request, searchTerm):
    getParameter = request.GET
    #print(getParameter)
    #value = getParameter['q'] 

    if util.listen_for_search(getParameter): # listens for user searching for a page.
        return util.search_for_page(getParameter)

    matchesList = util.match_for_entries(searchTerm)
    return render(request, "encyclopedia/search_results.html", {"entries": matchesList})

encyclopedia/templates/encyclopedia/createpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create New Page
{% endblock %}

{% block body %}

    <form action="{% url 'encyclopedia:createNewPage' %}" method="post">
        {% csrf_token %}
        
        <p>{{ form.title.label }}</p>
        <p>{{ form.title }}</p>
        <p>{{ form.content }}</p>
        <input type="submit" value="Create Page">
    </form>

{% endblock %}

<!--        {{ form.as_p }}
-->        

encyclopedia/templates/encyclopedia/editpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Page
{% endblock title %}

{% block body %}
    <h1>{{ title }}</h1>

    <form action="" method=post>
        {% csrf_token %}

        {{ form.as_p }}

        <input type="submit" value="Apply Changes">
    </form>

{% endblock body %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:entryPage' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form>
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:createNewPage' %}">Create New Page</a>
                </div>
                <div>
                    <a href=" {% url 'encyclopedia:randomPage' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock title %}

{% block body %}
    {{ bodyContent|safe }}

    <button><a href="{% url "encyclopedia:editPage" title %}">Edit this page</a></button>

{% endblock body%}

encyclopedia/templates/encyclopedia/search_results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Did you mean...</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:entryPage' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}